---
# $yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
steps:
  - label: "Triggering pipelines"
    plugins:
      monorepo-diff#v1.5.1:
        diff: ".buildkite/diff ${BUILDKITE_COMMIT}"
        wait: true
        watch:
          # if our Renovate configuration is amended, then make sure we have well-formed config
          # for more info, see https://docs.elastic.dev/plat-prod-team/service-catalogue/renovate/testing-renovate-changes
          - path: "renovate.json"
            config:
              label: "Verify Renovate configuration"
              command: "renovate-config-validator"
              agents:
                image: "docker.elastic.co/ci-agent-images/pipelib:0.20.0@sha256:1a34e41176f8e9870170d2f2ec1a4477adfc8d8c0c795f6769fd4bcd79527f38"
          # if our catalog-info.yaml is changed, make sure it's well-formed according to our internal standards as well as Backstage's validation
          - path: "catalog-info.yaml"
            config:
              command: "/agent/check-catalog-info.sh"
              agents:
                image: "docker.elastic.co/ci-agent-images/pipelib:0.20.0@sha256:1a34e41176f8e9870170d2f2ec1a4477adfc8d8c0c795f6769fd4bcd79527f38"
          - default:
              config:
                label: ":pipeline: Upload default Pipeline"
                command: "buildkite-agent pipeline upload .buildkite/default-pipeline.yml"
